# ----------------------------------------------------------------------------
#
# Package             : junit5
# Source Repo         : https://github.com/spring-projects/junit5
# Travis Job Link     : https://github.com/junit-team/junit5.git
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: java

jdk: 
  - openjdk8
  - openjdk11
  - openjdk15
os:
  - linux
arch:
  - amd64
  - ppc64le

script :
    - ./gradlew build
    - ./gradlew clean test
    - ./gradlew --version
    - ./gradlew javaToolchains -Porg.gradle.java.installations.auto-download=false
    - ./gradlew --no-parallel --stacktrace -Dplatform.tooling.support.tests.enabled=true -PenableJaCoCo -Porg.gradle.java.installations.auto-download=false build jacocoRootReport
