# ----------------------------------------------------------------------------
#
# Package             : junit5
# Source Repo         : https://github.com/spring-projects/junit5
# Travis Job Link     : https://github.com/junit-team/junit5.git
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: java

jdk:
   - openjdk11
os:
  - linux
arch:
  - amd64
  - ppc64le
before_install:
   - if [ "$TRAVIS_CPU_ARCH" = "ppc64le" ]; then
       sudo wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add - ;
       sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ ;
       sudo rm -rf /var/lib/apt/lists/* ;
       sudo apt-get update -y ;
       sudo apt install adoptopenjdk-10-hotspot -y ;
       sudo apt remove adoptopenjdk-11-hotspot -y ;
       java -version ;
     fi
script :
    - ./gradlew build
    - ./gradlew clean test
    - ./gradlew --version
    - ./gradlew javaToolchains -Porg.gradle.java.installations.auto-download=false
    -  ./gradlew --no-parallel --stacktrace -Dplatform.tooling.support.tests.enabled=true -PenableJaCoCo -Porg.gradle.java.installations.auto-download=false build jacocoRootReport
